version: '3'

services:
  newman:
    container_name: newman
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    command: ./run_tests.sh
    depends_on:
      - komodefi

  komodefi:
    container_name: komodefi
    env_file:
      - ./mm2/.env
    build:
      context: ./mm2
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - ./:/mm2
    ports:
      - 127.0.0.1:7783:7783
      - 127.0.0.1:42945:42845
      - 127.0.0.1:42955:42855
    logging:
      driver: none
    restart: always
