version: '3'

services:
  postman-tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NEWMAN_REPORTERS=cli,html
      - NEWMAN_REPORTER_HTML_TEMPLATE='template.hbs'
      - NEWMAN_REPORTER_HTML_EXPORT='newman-report.html
      - API_KEY="PMAK-65e46ac603f87a0001c62502-416d2a73e2ea807129a1808bf4103837fc"
      - COLLECTION_ID="12719479-46138bcd-769f-4ed1-b232-3850b805c9ec"
      - ENV_ID="33262259-1713ed0b-0c15-47b6-aaad-9ceb9a4033c9"
    command: ./run_tests.sh
    depends_on:
      - komodefi

  komodefi:
    container_name: komodefi
    env_file:
      - ./mm2/.env
    build:
      context: ./mm2
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - ./:/mm2
    ports:
      - 127.0.0.1:7783:7783
      - 127.0.0.1:42945:42845
      - 127.0.0.1:42955:42855
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    restart: always
