version: '3.7'

x-zcash-params-volume:
  &zcash-params
  type: bind
  read_only: true
  source: ${HOME}/.zcash-params
  target: /home/komodian/.zcash-params

services:
  newman:
    container_name: newman
    env_file:
      - ./newman/.env
    build:
      context: ./newman
      dockerfile: Dockerfile
    command: ./run_tests.sh
    depends_on:
      - komodefi
      - komodod_a
      - komodod_b

  komodefi:
    container_name: komodefi
    env_file:
      - ./komodefi/.env
    build:
      context: ./komodefi
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - ./:/komodefi
    ports:
      - 127.0.0.1:7783:7783
      - 0.0.0.0:42845:42845
      - 0.0.0.0:42855:42855
    logging:
      driver: none
    restart: always
    networks:
      custom_net:
        ipv4_address: 10.9.8.7

  komodod_a:
    container_name: komodod_a
    env_file:
      - ./komodo/.env_a
    build:
      context: ./komodo
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
        - SERVICE_CLI="komodo-cli -ac_name=QATEST"
    ports:
      - "0.0.0.0:9688:9688"
      - "127.0.0.1:9689:9689"
    volumes:
      - <<: *zcash-params
      - ${HOME}/.komodo/QATEST_A:/home/komodian/.komodo/QATEST
    restart: always
    stop_grace_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    command: ["/run.sh"]
    networks:
      custom_net:
        ipv4_address: 10.9.8.6

  komodod_b:
    container_name: komodod_b
    env_file:
      - ./komodo/.env_b
    build:
      context: ./komodo
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
        - SERVICE_CLI="komodo-cli -ac_name=QATEST"
    ports:
      - "0.0.0.0:9788:9788"
      - "127.0.0.1:9789:9789"
    volumes:
      - <<: *zcash-params
      - ${HOME}/.komodo/QATEST_B:/home/komodian/.komodo/QATEST
    restart: always
    stop_grace_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    command: ["/run.sh"]
    networks:
      custom_net:
        ipv4_address: 10.9.8.5


networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.9.0.0/16
          gateway: 10.9.8.1
