name: Run tests

on:
  workflow_dispatch:
    inputs:
      qase_api_base_url:
        description: 'Qase API URL'
        required: true
      qase_report:
        description: 'Enabled/disabled reporting to Qase'
        required: true
      qase_project_code:
        description: 'Qase project code'
        required: true
      qase_run_id:
        description: 'Qase Run ID'
        required: true
      qase_run_complete:
        description: 'Complete Qase Run'
        required: true

env:
  QASE_API_BASE_URL: ${{ inputs.qase_api_base_url }}
  QASE_REPORT: ${{ inputs.qase_report }}
  QASE_PROJECT_CODE: ${{ inputs.qase_project_code }}
  QASE_RUN_ID: ${{ inputs.qase_run_id }}
  QASE_RUN_COMPLETE: ${{ inputs.qase_run_complete }}
  QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}

jobs:
  build-js:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: qase-tms/qase-link-run@main
        env:
          QASE_API_TOKEN: ${{ env.QASE_API_TOKEN }}
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
  
  report:
    needs: build-js
    runs-on: ubuntu-latest
    steps:
      - uses: qase-tms/qase-report@main
        env:
          QASE_API_TOKEN: ${{ env.QASE_API_TOKEN }}
          QASE_API_BASE_URL: ${{ env.QASE_API_BASE_URL }}
          QASE_PROJECT_CODE: ${{ env.QASE_PROJECT_CODE }}
          QASE_RUN_ID: ${{ env.QASE_RUN_ID }}
          QASE_RUN_COMPLETE: ${{ env.QASE_RUN_COMPLETE }}          
          QASE_RUN_NAME:	'Basic DeFi tests'
          QASE_RUN_DESCRIPTION: 'Newman tests'
          QASE_LOGGING: debug
